Merge pyth cli client
near/near-multichain-xchain-relayer pull request #28
Opened 2024-08-12 15:51 UTC by encody

2024-08-12 16:06 UTC, encody commented
@anthony-near @ravigautham

2024-08-12 19:04 UTC, anthony-near approved these changes

2024-08-12 19:20 UTC, anthony-near requested changes
linter isn't happy https://github.com/near/multichain-gas-station-contract/actions/runs/10355309786/job/28670559881?pr=28

2024-08-13 05:00 UTC, encody commented
"works on my machine" be like...

working on it

2024-10-02 06:52 UTC, merged